name: pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Generate document
        run: |
          brew install mint
          mint install
          mint build --skip-service-worker --relative
      - name: Publish Documentation on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
